server:
  port: ${PORT}
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://${PGSQL_HOST}:5432/${PGSQL_DBNAME}
      username: ${PGSQL_USER}
      password: ${PGSQL_PASS}
  flyway:
    locations: classpath:db/migration

