CREATE TABLE warehouse
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_warehouse PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255),
    quality                 INTEGER,
    purchase_price          BIGINT,
    purchase_price_with_vat BIGINT,
    sale_price              BIGINT,
    sale_price_with_vat     BIGINT,
    warehouse_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id);